services:
  db:
    image: postgres:17-alpine
    command: "-d 1"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  meilisearch:
    image: getmeili/meilisearch:v1.26
    restart: unless-stopped
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    volumes:
      - meili_data:/meili_data
    ports:
      - 7700:7700

  api:
    build: ./apps/api
    container_name: tsuika-api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      meilisearch:
        condition: service_started
      db:
        condition: service_healthy
    environment:
      DOMAIN: ${DOMAIN:-localhost}
      HOST_URL: ${HOST_URL}

      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB_NAME}"

      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN}
      CORS_ORIGIN_BROWSER_EXTENSION: ${CORS_ORIGIN_BROWSER_EXTENSION}

      ENABLE_EMAIL_VERIFICATION: ${ENABLE_EMAIL_VERIFICATION:-false}
      RESEND_API_KEY: ${RESEND_API_KEY}
      JWT_SECRET: ${JWT_SECRET}

      MEILI_HOST: ${MEILI_HOST:-http://meilisearch:7700}
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    volumes:
      - api_data:/app/data

  frontend:
    build:
      context: ./apps/frontend
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_GENAI_API_KEY: ${VITE_GENAI_API_KEY}
    container_name: tsuika
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  meili_data:
  object_store:
  postgres_data:
  api_data:
