/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedSaveBookmarkRouteRouteImport } from './routes/_authenticated/save-bookmark/route'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHomeIndexRouteImport } from './routes/_authenticated/_home/index'
import { Route as AuthVerify2faIndexRouteImport } from './routes/_auth/verify-2fa/index'
import { Route as AuthEmailVerificationIndexRouteImport } from './routes/_auth/email-verification/index'
import { Route as AuthenticatedBookmarksSlugRouteImport } from './routes/_authenticated/bookmarks/$slug'
import { Route as AuthenticatedSettingsProfileIndexRouteImport } from './routes/_authenticated/settings/profile/index'
import { Route as AuthenticatedSettingsAppearanceIndexRouteImport } from './routes/_authenticated/settings/appearance/index'
import { Route as AuthenticatedSettingsAccountIndexRouteImport } from './routes/_authenticated/settings/account/index'
import { Route as PublicUnameFolderIdRouteImport } from './routes/_public/$uname.folder.$id'
import { Route as AuthenticatedBookmarksBookmarkBIdRouteImport } from './routes/_authenticated/bookmarks/_bookmark/b.$id'
import { Route as AuthenticatedBookmarksFolderFolderSIdRouteImport } from './routes/_authenticated/bookmarks/_folder/folder.s.$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSaveBookmarkRouteRoute =
  AuthenticatedSaveBookmarkRouteRouteImport.update({
    id: '/save-bookmark',
    path: '/save-bookmark',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHomeIndexRoute = AuthenticatedHomeIndexRouteImport.update({
  id: '/_home/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthVerify2faIndexRoute = AuthVerify2faIndexRouteImport.update({
  id: '/verify-2fa/',
  path: '/verify-2fa/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthEmailVerificationIndexRoute =
  AuthEmailVerificationIndexRouteImport.update({
    id: '/email-verification/',
    path: '/email-verification/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthenticatedBookmarksSlugRoute =
  AuthenticatedBookmarksSlugRouteImport.update({
    id: '/bookmarks/$slug',
    path: '/bookmarks/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsProfileIndexRoute =
  AuthenticatedSettingsProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceIndexRoute =
  AuthenticatedSettingsAppearanceIndexRouteImport.update({
    id: '/appearance/',
    path: '/appearance/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountIndexRoute =
  AuthenticatedSettingsAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const PublicUnameFolderIdRoute = PublicUnameFolderIdRouteImport.update({
  id: '/_public/$uname/folder/$id',
  path: '/$uname/folder/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBookmarksBookmarkBIdRoute =
  AuthenticatedBookmarksBookmarkBIdRouteImport.update({
    id: '/bookmarks/_bookmark/b/$id',
    path: '/bookmarks/b/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookmarksFolderFolderSIdRoute =
  AuthenticatedBookmarksFolderFolderSIdRouteImport.update({
    id: '/bookmarks/_folder/folder/s/$id',
    path: '/bookmarks/folder/s/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/save-bookmark': typeof AuthenticatedSaveBookmarkRouteRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/bookmarks/$slug': typeof AuthenticatedBookmarksSlugRoute
  '/email-verification': typeof AuthEmailVerificationIndexRoute
  '/verify-2fa': typeof AuthVerify2faIndexRoute
  '/': typeof AuthenticatedHomeIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/$uname/folder/$id': typeof PublicUnameFolderIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountIndexRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceIndexRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileIndexRoute
  '/bookmarks/b/$id': typeof AuthenticatedBookmarksBookmarkBIdRoute
  '/bookmarks/folder/s/$id': typeof AuthenticatedBookmarksFolderFolderSIdRoute
}
export interface FileRoutesByTo {
  '/save-bookmark': typeof AuthenticatedSaveBookmarkRouteRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/bookmarks/$slug': typeof AuthenticatedBookmarksSlugRoute
  '/email-verification': typeof AuthEmailVerificationIndexRoute
  '/verify-2fa': typeof AuthVerify2faIndexRoute
  '/': typeof AuthenticatedHomeIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/$uname/folder/$id': typeof PublicUnameFolderIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountIndexRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceIndexRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileIndexRoute
  '/bookmarks/b/$id': typeof AuthenticatedBookmarksBookmarkBIdRoute
  '/bookmarks/folder/s/$id': typeof AuthenticatedBookmarksFolderFolderSIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/save-bookmark': typeof AuthenticatedSaveBookmarkRouteRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_authenticated/bookmarks/$slug': typeof AuthenticatedBookmarksSlugRoute
  '/_auth/email-verification/': typeof AuthEmailVerificationIndexRoute
  '/_auth/verify-2fa/': typeof AuthVerify2faIndexRoute
  '/_authenticated/_home/': typeof AuthenticatedHomeIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_public/$uname/folder/$id': typeof PublicUnameFolderIdRoute
  '/_authenticated/settings/account/': typeof AuthenticatedSettingsAccountIndexRoute
  '/_authenticated/settings/appearance/': typeof AuthenticatedSettingsAppearanceIndexRoute
  '/_authenticated/settings/profile/': typeof AuthenticatedSettingsProfileIndexRoute
  '/_authenticated/bookmarks/_bookmark/b/$id': typeof AuthenticatedBookmarksBookmarkBIdRoute
  '/_authenticated/bookmarks/_folder/folder/s/$id': typeof AuthenticatedBookmarksFolderFolderSIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/save-bookmark'
    | '/settings'
    | '/login'
    | '/register'
    | '/bookmarks/$slug'
    | '/email-verification'
    | '/verify-2fa'
    | '/'
    | '/settings/'
    | '/$uname/folder/$id'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/profile'
    | '/bookmarks/b/$id'
    | '/bookmarks/folder/s/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/save-bookmark'
    | '/login'
    | '/register'
    | '/bookmarks/$slug'
    | '/email-verification'
    | '/verify-2fa'
    | '/'
    | '/settings'
    | '/$uname/folder/$id'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/profile'
    | '/bookmarks/b/$id'
    | '/bookmarks/folder/s/$id'
  id:
    | '__root__'
    | '/_auth'
    | '/_authenticated'
    | '/_authenticated/save-bookmark'
    | '/_authenticated/settings'
    | '/_auth/login'
    | '/_auth/register'
    | '/_authenticated/bookmarks/$slug'
    | '/_auth/email-verification/'
    | '/_auth/verify-2fa/'
    | '/_authenticated/_home/'
    | '/_authenticated/settings/'
    | '/_public/$uname/folder/$id'
    | '/_authenticated/settings/account/'
    | '/_authenticated/settings/appearance/'
    | '/_authenticated/settings/profile/'
    | '/_authenticated/bookmarks/_bookmark/b/$id'
    | '/_authenticated/bookmarks/_folder/folder/s/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PublicUnameFolderIdRoute: typeof PublicUnameFolderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/save-bookmark': {
      id: '/_authenticated/save-bookmark'
      path: '/save-bookmark'
      fullPath: '/save-bookmark'
      preLoaderRoute: typeof AuthenticatedSaveBookmarkRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/_home/': {
      id: '/_authenticated/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedHomeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_auth/verify-2fa/': {
      id: '/_auth/verify-2fa/'
      path: '/verify-2fa'
      fullPath: '/verify-2fa'
      preLoaderRoute: typeof AuthVerify2faIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/email-verification/': {
      id: '/_auth/email-verification/'
      path: '/email-verification'
      fullPath: '/email-verification'
      preLoaderRoute: typeof AuthEmailVerificationIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/bookmarks/$slug': {
      id: '/_authenticated/bookmarks/$slug'
      path: '/bookmarks/$slug'
      fullPath: '/bookmarks/$slug'
      preLoaderRoute: typeof AuthenticatedBookmarksSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/profile/': {
      id: '/_authenticated/settings/profile/'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance/': {
      id: '/_authenticated/settings/appearance/'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account/': {
      id: '/_authenticated/settings/account/'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_public/$uname/folder/$id': {
      id: '/_public/$uname/folder/$id'
      path: '/$uname/folder/$id'
      fullPath: '/$uname/folder/$id'
      preLoaderRoute: typeof PublicUnameFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bookmarks/_bookmark/b/$id': {
      id: '/_authenticated/bookmarks/_bookmark/b/$id'
      path: '/bookmarks/b/$id'
      fullPath: '/bookmarks/b/$id'
      preLoaderRoute: typeof AuthenticatedBookmarksBookmarkBIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookmarks/_folder/folder/s/$id': {
      id: '/_authenticated/bookmarks/_folder/folder/s/$id'
      path: '/bookmarks/folder/s/$id'
      fullPath: '/bookmarks/folder/s/$id'
      preLoaderRoute: typeof AuthenticatedBookmarksFolderFolderSIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthEmailVerificationIndexRoute: typeof AuthEmailVerificationIndexRoute
  AuthVerify2faIndexRoute: typeof AuthVerify2faIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthEmailVerificationIndexRoute: AuthEmailVerificationIndexRoute,
  AuthVerify2faIndexRoute: AuthVerify2faIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSettingsAccountIndexRoute: typeof AuthenticatedSettingsAccountIndexRoute
  AuthenticatedSettingsAppearanceIndexRoute: typeof AuthenticatedSettingsAppearanceIndexRoute
  AuthenticatedSettingsProfileIndexRoute: typeof AuthenticatedSettingsProfileIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
    AuthenticatedSettingsAccountIndexRoute:
      AuthenticatedSettingsAccountIndexRoute,
    AuthenticatedSettingsAppearanceIndexRoute:
      AuthenticatedSettingsAppearanceIndexRoute,
    AuthenticatedSettingsProfileIndexRoute:
      AuthenticatedSettingsProfileIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSaveBookmarkRouteRoute: typeof AuthenticatedSaveBookmarkRouteRoute
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedBookmarksSlugRoute: typeof AuthenticatedBookmarksSlugRoute
  AuthenticatedHomeIndexRoute: typeof AuthenticatedHomeIndexRoute
  AuthenticatedBookmarksBookmarkBIdRoute: typeof AuthenticatedBookmarksBookmarkBIdRoute
  AuthenticatedBookmarksFolderFolderSIdRoute: typeof AuthenticatedBookmarksFolderFolderSIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSaveBookmarkRouteRoute: AuthenticatedSaveBookmarkRouteRoute,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedBookmarksSlugRoute: AuthenticatedBookmarksSlugRoute,
  AuthenticatedHomeIndexRoute: AuthenticatedHomeIndexRoute,
  AuthenticatedBookmarksBookmarkBIdRoute:
    AuthenticatedBookmarksBookmarkBIdRoute,
  AuthenticatedBookmarksFolderFolderSIdRoute:
    AuthenticatedBookmarksFolderFolderSIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicUnameFolderIdRoute: PublicUnameFolderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
