name: tsuika-dev

networks:
  tsuika_default:

services:
  postgres:
    image: postgres:18-alpine
    command: "-d 1"
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  meilisearch:
    image: getmeili/meilisearch:v1.26
    environment:
      MEILI_HOST: ${MEILI_HOST}
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    volumes:
      - meili_data:/meili_data
    ports:
      - 7700:7700

  rustfs:
    image: rustfs/rustfs:latest
    environment:
      RUSTFS_ACCESS_KEY: ${S3_ACCESS_KEY_ID:-rustfsadmin}
      RUSTFS_SECRET_KEY: ${S3_SECRET_ACCESS_KEY:-rustfsadmin}
      RUSTFS_CONSOLE_ENABLE: true
      RUSTFS_SERVER_DOMAINS: localhost
    volumes:
      - rustfs_data:/data
    ports:
      - 9000:9000
      - 9001:9001

volumes:
  db_data:
  meili_data:
  rustfs_data:
